@startuml

title Diagramme de classes - Système de point de vente

class Produit {
  id: int
  nom: str
  description: str
  categorie: str
  prix_unitaire: float
}

class Vente {
  id: int
  total: float
}

class LigneVente {
  id: int
  quantite: int
  prix_total: float
}

class Utilisateur {
  id: int
  nom: str
  identifiant: str
}

class Stock { 
  id: int 
  quantite: int
  product: Product
}

class Magasin { 
  id: int
  name: str
  location: str
}

class CentreLogistique { 
  id: int
  product: str
  quantite: int
}

' Relations entre classes
Vente "1" -- "0..*" LigneVente : contient >
LigneVente "0..*" --> "1" Produit : réfert à un >
Vente "*" --> "1" Utilisateur : < fait
Produit "1" --> "1" Stock : a > 
Magasin "1" --> "0..*" Stock: contient du > 
Magasin "1"--> "0..*" Vente : ont des
CentreLogistique "1" --> "0..*" Produit: ont des
@enduml