@startuml  
top to bottom direction
title Diagramme de déploiement - Système de magasin
node "<<device>>\n Magasin" { 
    artifact "Browser" { 
        file "HTML templates"
    }
}

node "<<server>>\nWeb Server" { 
    artifact { 
        artifact "Application Django" { 
            file "controller.py"
            file "models.py"
            file "views.py"
        }
    } 
}



database "<<device>>\nDB server" { 
    artifact { 
        agent "PostgreSQL server"
    }
}


"controller.py" <--> "models.py" : uses
"controller.py" <--> "views.py" : uses
"models.py" <--> "views.py" : uses
"<<device>>\n Magasin" --> "<<server>>\nWeb Server" : HTTP requests
"<<server>>\nWeb Server" --> "<<device>>\nDB server" : ORM via SQLAlchemy
@enduml 