@startuml
hide circle
hide members
top to bottom direction
title Diagramme de composant - Système de point de vente

package "web" { 
    component browser
}

package caisse {

    folder "templates"
    component "views"
    component "controleurs"
    component "models"
    
}
package "database" {
    component "PostgreSQL"
}

browser --> templates : "Requêtes HTTP" 
models --> PostgreSQL : "Requêtes SQL"

views <--> controleurs
controleurs <--> models
models <--> views

templates --> views : "Rendu des vues"
@enduml