@startuml
skinparam style strictuml
skinparam defaultfontname Verdana
skinparam sequence {
    MessageAlign center
}
title Diagramme de séquence UC4 - Consulter le stock d'un produit

participant "user" as user
participant "app" as app
participant "database" as db 

user -> app : Consulter le stock d'un produit 
app -> db : check_stock(id_product)
db --> app : int: stock
app --> user : int: stock

@enduml